create type public.app_role as enum ('admin', 'teacher', 'student');
create type public.account_status as enum ('pending', 'active', 'disabled');
create type public.attendance_status as enum ('present', 'late', 'absent');

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique,
  username text not null unique check (length(username) between 3 and 50),
  full_name text not null check (length(full_name) between 1 and 120),
  role public.app_role not null,
  status public.account_status not null default 'pending',
  created_at timestamptz not null default now()
);

create table public.academic_years (
  id smallint primary key,
  year_level smallint not null unique check (year_level between 1 and 6),
  name text not null unique
);
create table public.semesters (
  id smallint primary key,
  academic_year_id smallint not null references public.academic_years(id),
  semester_number smallint not null check (semester_number in (1, 2)),
  name text not null,
  unique (academic_year_id, semester_number)
);
create table public.classes (
  id integer generated by default as identity primary key,
  academic_year_id smallint not null references public.academic_years(id),
  name text not null unique
);
create table public.subjects (
  id integer generated by default as identity primary key,
  code text,
  name text not null check (length(name) between 1 and 120),
  semester_id smallint not null references public.semesters(id),
  teacher_registration_enabled boolean not null default true,
  unique (semester_id, code)
);
create table public.students (
  id bigint generated by default as identity primary key,
  user_id uuid not null unique references public.profiles(id) on delete cascade,
  student_no text not null unique,
  class_id integer not null references public.classes(id),
  semester_id smallint not null references public.semesters(id),
  device_uuid text,
  created_at timestamptz not null default now()
);
create table public.teachers (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now()
);
create table public.teacher_terms (
  id integer generated by default as identity primary key,
  teacher_id uuid not null references public.teachers(user_id) on delete cascade,
  semester_id smallint not null references public.semesters(id),
  class_id integer not null references public.classes(id),
  unique (teacher_id, semester_id, class_id)
);
create table public.teacher_subjects (
  id integer generated by default as identity primary key,
  teacher_term_id integer not null references public.teacher_terms(id) on delete cascade,
  subject_id integer not null references public.subjects(id),
  unique (teacher_term_id, subject_id)
);
create table public.attendance_sessions (
  id bigint generated by default as identity primary key,
  teacher_id uuid not null references public.teachers(user_id),
  teacher_subject_id integer not null references public.teacher_subjects(id),
  title text not null check (length(title) between 1 and 150),
  qr_token_hash text not null unique,
  qr_display_token text,
  starts_at timestamptz not null default now(),
  ended_at timestamptz,
  active boolean not null default true
);
create unique index one_active_session_per_teacher on public.attendance_sessions(teacher_id) where active;
create table public.attendance (
  id bigint generated by default as identity primary key,
  session_id bigint not null references public.attendance_sessions(id) on delete cascade,
  student_id bigint not null references public.students(id),
  status public.attendance_status not null default 'present',
  latitude double precision,
  longitude double precision,
  accuracy double precision,
  distance_from_classroom double precision,
  recorded_at timestamptz not null default now(),
  unique (session_id, student_id)
);
create index attendance_recorded_at_idx on public.attendance(recorded_at);
create index attendance_session_idx on public.attendance(session_id);

create or replace function public.require_active_attendance_session()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare session_is_active boolean;
begin
  select s.active into session_is_active
  from public.attendance_sessions s
  where s.id = new.session_id
  for update;
  if session_is_active is distinct from true then
    raise exception 'Attendance session has ended.' using errcode = 'P0001';
  end if;
  return new;
end;
$$;
create trigger attendance_only_during_active_session
before insert on public.attendance
for each row execute function public.require_active_attendance_session();

insert into public.academic_years(id, year_level, name) values
  (1,1,'1st Year'),(2,2,'2nd Year'),(3,3,'3rd Year'),
  (4,4,'4th Year'),(5,5,'5th Year'),(6,6,'6th Year');
insert into public.semesters(id, academic_year_id, semester_number, name) values
  (11,1,1,'1st Semester'),(12,1,2,'2nd Semester'),
  (21,2,1,'1st Semester'),(22,2,2,'2nd Semester'),
  (31,3,1,'1st Semester'),(32,3,2,'2nd Semester'),
  (41,4,1,'1st Semester'),(42,4,2,'2nd Semester'),
  (51,5,1,'1st Semester'),(52,5,2,'2nd Semester'),
  (61,6,1,'1st Semester'),(62,6,2,'2nd Semester');
insert into public.classes(academic_year_id, name) values
  (1,'1IT'),(2,'2IT'),(3,'3IT'),(4,'4IT'),(4,'4IT1'),(5,'5IT'),(6,'6IT');
insert into public.subjects(code,name,semester_id) values
  ('CEIT-2001','C Programming',11),
  ('CEIT-1000','Introduction to Computer System',12),
  ('CEIT-3011','Objective Oriented Programming',21),('CEIT-3010','Digital Electronics',21),
  ('CEIT-3020','Engineering Circuit Analysis',21),
  ('CEIT-4002','Digital Communication',22),('CEIT-4021','Advanced Java Programming',22),
  ('CEIT-4031','Database Management System',22),('CEIT-4041','Data Structure and Algorithm',22),
  ('IT-31055','Data Structure',31),('IT-31022','Computer Networks',31),
  ('IT-31035','Web Development Technologies II',31),('IT-31016','Database Management System',31),
  ('IT-32045','Programming Language in Java',31),
  ('IT-32055','Data Structure',32),('IT-32022','Computer Networks',32),
  ('IT-32035','Web Development Technologies II',32),('IT-32016','Database Management System',32),
  ('IT-32045','Programming Language in Java',32),
  ('IT-41017','Modern Control Systems',41),('IT-41032','Advanced Computer Networks',41),
  ('IT-41023','Computer Architecture and Organization',41),('IT-41033','Operating Systems',41),
  ('IT-41026','Advanced Data Management Techniques',41),
  ('IT-42017','Modern Control Systems',42),('IT-42032','Advanced Computer Networks',42),
  ('IT-42023','Computer Architecture and Organization',42),('IT-42033','Operating Systems',42),
  ('IT-42026','Advanced Data Management Techniques',42),
  ('IT-51065','Software Engineering',51),('IT-51043','Embedded Systems',51),
  ('IT-51014','Cloud Computing',51),('IT-51027','Digital Signal Processing',51),
  ('IT-51037','Digital Image Processing',51),
  ('IT-52047','Artificial Intelligence',52),('IT-52043','Embedded Systems',52),
  ('IT-52037','Digital Image Processing',52),('IT-52065','Software Engineering',52),
  ('IT-52042','Cryptography and Network Security',52),
  ('IT-61075','Project Management',61),('IT-61062','Wireless and Mobile Communications',61),
  ('IT-61052','Network Planning and Management',61);

alter table public.profiles enable row level security;
alter table public.academic_years enable row level security;
alter table public.semesters enable row level security;
alter table public.classes enable row level security;
alter table public.subjects enable row level security;
alter table public.students enable row level security;
alter table public.teachers enable row level security;
alter table public.teacher_terms enable row level security;
alter table public.teacher_subjects enable row level security;
alter table public.attendance_sessions enable row level security;
alter table public.attendance enable row level security;

create policy "Academic years are public catalog data" on public.academic_years for select to anon, authenticated using (true);
create policy "Semesters are public catalog data" on public.semesters for select to anon, authenticated using (true);
create policy "Classes are public catalog data" on public.classes for select to anon, authenticated using (true);
create policy "Subjects are public catalog data" on public.subjects for select to anon, authenticated using (teacher_registration_enabled);

grant usage on schema public to anon, authenticated, service_role;
grant select on public.academic_years, public.semesters, public.classes, public.subjects to anon, authenticated;
grant all privileges on all tables in schema public to service_role;
grant usage, select on all sequences in schema public to service_role;
